## Memoria
vm_memory_high_watermark.relative = 0.4

## Disco
disk_free_limit.relative = 1.5

## Conexiones
channel_max = 2048
max_connections = 5000

## Seguridad
loopback_users.guest = false

## Management
management.tcp.port = 15672
management.tcp.ip = 0.0.0.0

## Logs
log.console = true
log.console.level = info

## Definitions (opcional)
management.load_definitions = /etc/rabbitmq/definitions.json
